Repository dopedao/dope-monorepo, pull requests merged in 2021-12, with the labels that each got.

#139 fix: add name length validation and alien skin color when configuring a hustler
  packages/web/components/PanelColorSelector.tsx
  packages/web/components/PanelFooter.tsx
  packages/web/components/hustler/ConfigurationControls.tsx
  packages/web/components/hustler/NameControls.tsx
  packages/web/features/hustlers/components/ConfigureHustler/index.tsx
  packages/web/src/HustlerConfig.ts
Labels: bug, enhancement

#145 fix: removes native alert to switch network
  packages/web/src/hooks/web3.ts
Labels: enhancement

#146 New customize hustler UI
  packages/web/src/components/AppWindow.tsx
  packages/web/src/components/AppWindowNavBar.tsx
  packages/web/src/components/ConnectWallet.tsx
  packages/web/src/components/Container.tsx
  packages/web/src/components/DesktopIcon.tsx
  packages/web/src/components/DesktopIconList.tsx
  packages/web/src/components/DesktopWindow.tsx
  packages/web/src/components/Dialog.tsx
  packages/web/src/components/MarketFilterBar.tsx
  packages/web/src/components/PanelColorSelector.tsx
  packages/web/src/components/StackedResponsiveContainer.tsx
  packages/web/src/components/dope/DopeTable.tsx
  packages/web/src/components/hustler/ConfigurationControls.tsx
  packages/web/src/components/hustler/HairSelector.tsx
  packages/web/src/components/hustler/InitiationInfo.tsx
  packages/web/src/components/hustler/NameControls.tsx
  packages/web/src/components/hustler/SexSelector.tsx
  packages/web/src/components/panels/ApprovePaper.tsx
  packages/web/src/features/hustlers/components/ConfigureHustler/index.tsx
  packages/web/src/features/hustlers/components/Stepper/index.tsx
  packages/web/src/pages/_app.tsx
  packages/web/src/pages/dope.tsx
  packages/web/src/pages/dope/unbundle-success.tsx
  packages/web/src/pages/gangsta-party.tsx
  packages/web/src/pages/hustlers/[id]/customize.tsx
  packages/web/src/pages/hustlers/index.tsx
  packages/web/src/pages/hustlers/mint-success.tsx
  packages/web/src/pages/index.tsx
  packages/web/src/pages/swap-meet.tsx
  packages/web/src/ui/components/Accordion/index.tsx
  packages/web/src/ui/components/Accordion/styles.ts
  packages/web/src/ui/styles/GlobalStyles.tsx
  packages/web/src/ui/styles/breakpoints.ts
  packages/web/src/ui/styles/components.tsx
  packages/web/src/ui/styles/mixins.tsx
  packages/web/src/ui/styles/reset.css
  packages/web/src/ui/styles/theme.ts
  packages/web/src/ui/svg/Check.tsx
  packages/web/src/ui/svg/ChevronRight.tsx
  packages/web/src/ui/svg/CollapseArrowsClosed.tsx
  packages/web/src/ui/svg/CollapseArrowsOpen.tsx
  packages/web/src/ui/svg/ConnectWallet.tsx
  packages/web/src/ui/svg/Ethereum.tsx
  packages/web/src/ui/svg/Spinner/index.tsx
  packages/web/src/ui/svg/Spinner/styles.ts
Labels: enhancement

#151 styling: show alert when there is not enough
  packages/web/src/features/hustlers/modules/Approve/index.tsx
Labels: enhancement

#156 fix: show og title for og hustlers only
  packages/web/src/components/hustler/RenderFromDopeId.tsx
  packages/web/src/components/hustler/RenderFromItemIds.tsx
  packages/web/src/features/hustlers/components/ConfigureHustler/index.tsx
Labels: bug

#157 styling: handle wording when transaction is processing and wait for it
  packages/web/src/features/hustlers/components/ConfigureHustler/index.tsx
Labels: enhancement

#159 chore: require wallet to be connected on hustlers page
  packages/web/src/components/AppWindow.tsx
  packages/web/src/pages/dope.tsx
  packages/web/src/pages/hustlers/index.tsx
Labels: enhancement

#171 Add opensea engine to go backend
  packages/api/ent/asset.go
  packages/api/ent/asset/asset.go
  packages/api/ent/asset/where.go
  packages/api/ent/asset_create.go
  packages/api/ent/asset_delete.go
  packages/api/ent/asset_query.go
  packages/api/ent/asset_update.go
  packages/api/ent/client.go
  packages/api/ent/config.go
  packages/api/ent/dope.go
  packages/api/ent/dope/dope.go
  packages/api/ent/dope/where.go
  packages/api/ent/dope_create.go
  packages/api/ent/dope_query.go
  packages/api/ent/dope_update.go
  packages/api/ent/ent.go
  packages/api/ent/gql_collection.go
  packages/api/ent/gql_edge.go
  packages/api/ent/gql_node.go
  packages/api/ent/gql_pagination.go
  packages/api/ent/gql_where_input.go
  packages/api/ent/hook/hook.go
  packages/api/ent/listing.go
  packages/api/ent/listing/listing.go
  packages/api/ent/listing/where.go
  packages/api/ent/listing_create.go
  packages/api/ent/listing_delete.go
  packages/api/ent/listing_query.go
  packages/api/ent/listing_update.go
  packages/api/ent/migrate/schema.go
  packages/api/ent/mutation.go
  packages/api/ent/predicate/predicate.go
  packages/api/ent/runtime.go
  packages/api/ent/schema/asset.go
  packages/api/ent/schema/dope.go
  packages/api/ent/schema/listing.go
  packages/api/ent/tx.go
  packages/api/gqlgen.yaml
  packages/api/graph/ent.graphql
  packages/api/graph/schema.graphql
Labels: WORK IN PROGRESS

#179 chore: bring back hustler initiate page
  packages/web/src/pages/dope.tsx
  packages/web/src/pages/hustlers/initiate.tsx
Labels: bug
