Repository dopedao/dope-monorepo, pull requests merged in 2021-11, with the labels that each got.

#67 styling: add telegram desktop icon
  packages/web/components/DesktopIcon.tsx
  packages/web/components/DesktopIconList.tsx
  packages/web/public/images/icon/telegram.svg
Labels: enhancement

#70 chore: connect to wallet if already authorized upon loading the page
  packages/web/components/AppWindow.tsx
  packages/web/components/DesktopIconList.tsx
  packages/web/components/DesktopWindow.tsx
  packages/web/components/DesktopWindowTitleBar/index.tsx
  packages/web/hooks/web3.ts
  packages/web/pages/hustler.tsx
  packages/web/pages/loot.tsx
  packages/web/pages/loot/[id].tsx
  packages/web/pages/swap-meet.tsx
  packages/web/pages/wallet.tsx
Labels: enhancement

#77 fix: show balance on the new pages
  packages/web/pages/hustlers/configure.tsx
  packages/web/pages/hustlers/initiate.tsx
Labels: bug

#81 feat: added the logic needed for the multi steps flow and the stepper component
  packages/web/components/StackedResponsiveContainer.tsx
  packages/web/components/hustler/InitiationFooterDopeContent.tsx
  packages/web/features/hustlers/HustlerProvider.tsx
  packages/web/features/hustlers/components/Stepper/index.tsx
  packages/web/features/hustlers/components/Stepper/styles.ts
  packages/web/features/hustlers/hooks/useDispatchHustler.tsx
  packages/web/features/hustlers/hooks/useHustler.tsx
  packages/web/features/hustlers/hustlerReducer.ts
  packages/web/features/hustlers/modules/Approve/index.tsx
  packages/web/features/hustlers/modules/Customize/index.tsx
  packages/web/features/hustlers/modules/Customize/styles.ts
  packages/web/features/hustlers/modules/Finalize/index.tsx
  packages/web/features/hustlers/modules/Initiate/index.tsx
  packages/web/features/hustlers/modules/Steps/index.tsx
  packages/web/features/hustlers/modules/Steps/styles.ts
  packages/web/features/hustlers/types/index.ts
  packages/web/pages/hustlers/configure.tsx
  packages/web/pages/hustlers/initiate.tsx
  packages/web/pages/loot/[id].tsx
  packages/web/svg/CarretRight.tsx
Labels: enhancement

#89 chore: move fetching wallet balance to the core wrapper component
  packages/web/components/AppWindow.tsx
  packages/web/components/DesktopWindow.tsx
  packages/web/pages/hustler.tsx
  packages/web/pages/hustlers/configure.tsx
  packages/web/pages/hustlers/initiate.tsx
  packages/web/pages/loot.tsx
  packages/web/pages/swap-meet.tsx
  packages/web/pages/wallet.tsx
Labels: enhancement

#88 Flesh out initiation screen
  packages/web/components/hustler/HustlerPanel.tsx
  packages/web/components/hustler/InitiationFooterDopeContent.tsx
  packages/web/features/hustlers/components/Stepper/index.tsx
  packages/web/features/hustlers/modules/Approve/index.tsx
  packages/web/features/hustlers/modules/Finalize/index.tsx
  packages/web/features/hustlers/modules/Initiate/index.tsx
  packages/web/pages/hustlers/configure.tsx
  packages/web/public/images/hustler/bridge_no_hustlers.png
  packages/web/public/images/hustler/bridge_with_hustlers.png
  packages/web/src/HustlerConfig.ts
  packages/web/styles/GlobalStyles.tsx
  packages/web/styles/theme.ts
Labels: WORK IN PROGRESS

#95 feat: cache tos
  packages/web/components/DesktopIconList.tsx
  packages/web/pages/terms-of-service.tsx
Labels: enhancement

#97 styling: handle loading state while txn is ongoing and handle rejection
  packages/web/features/hustlers/modules/Approve/index.tsx
  packages/web/svg/Spinner/index.tsx
  packages/web/svg/Spinner/styles.ts
Labels: enhancement

#107 feat: fetch hustlers on '/hustlers'
  packages/subgraph/l2/src/mapping.ts
  packages/web/apollo/queries/hustlers-wallet.graphql
  packages/web/components/DesktopWindowTitleBar/index.tsx
  packages/web/components/EthereumApolloProvider.tsx
  packages/web/pages/hustler.tsx
  packages/web/src/generated/graphql.ts
Labels: enhancement

#126 feat: add a button to add OP network
  packages/web/components/StickyNoteHustlerMint.tsx
  packages/web/hooks/web3.ts
  packages/web/public/images/icon/metamaskicon.svg
  packages/web/src/constants.ts
Labels: enhancement

#118 Chore/transfer single event
  packages/web/features/hustlers/modules/Approve/index.tsx
  packages/web/pages/hustlers/mint-success.tsx
Labels: enhancement
